INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, COLOR_CODE, STATUS) VALUES ('1', '前端', '#FF9900', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, COLOR_CODE, STATUS) VALUES ('2', '后端', '#CC0000', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, COLOR_CODE, STATUS) VALUES ('3', '数据库', '#3333FF', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, COLOR_CODE, STATUS) VALUES ('4', '服务器', '#66FF00', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, COLOR_CODE, STATUS) VALUES ('5', '测试', '#FFFF00', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, COLOR_CODE, STATUS) VALUES ('6', '运维', '#CC00FF', 'E');
