INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, STATUS) VALUES ('1', '前端', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, STATUS) VALUES ('2', '后端', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, STATUS) VALUES ('3', '数据库', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, STATUS) VALUES ('4', '服务器', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, STATUS) VALUES ('5', '测试', 'E');
INSERT INTO LIBRARY.ARTICLE_CATEGORY (ID, NAME, STATUS) VALUES ('6', '运维', 'E');